version: '3'
services:
  backend:
    image: golang:1.13.4
    container_name: exsample-backend
    tty: true
    volumes:
      - ./backend:/go
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: exsample-mysql
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
    expose:
      - 3306
    ports:
      - "3306:3306"

volumes:
  mysql_data: