// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Migrations   string
	UserProfiles string
	Users        string
}{
	Migrations:   "migrations",
	UserProfiles: "user_profiles",
	Users:        "users",
}
